-- 3월/ 여성/ 전화번호 !NULL / ID기준으로 오름차순
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH,'MM') ='03' AND TLNO IS NOT NULL AND GENDER ='W'
ORDER BY MEMBER_ID ASC
